-- CampusFlow seed data. Generated by scripts/generate-seed.mjs. Safe to run more than once.
-- Contains no users, passwords or secrets. Run AFTER migrations/001_initial_schema.sql.

-- Departments
insert into public.departments (name, code) values
  ('Computer Science', 'CSE'),
  ('Information Technology', 'IT'),
  ('Electronics', 'ECE'),
  ('Business Studies', 'BBA'),
  ('Arts & Design', 'ARTS'),
  ('Physical Education', 'PE')
on conflict (name) do nothing;

-- Event categories
insert into public.event_categories (name, description, icon) values
  ('Technical', 'Tech talks, expos and project showcases.', 'Cpu'),
  ('Cultural', 'Music, dance, drama and art.', 'Palette'),
  ('Sports', 'Tournaments, leagues and meets.', 'Trophy'),
  ('Workshop', 'Hands-on sessions to build new skills.', 'Wrench'),
  ('Hackathon', 'Team build challenges.', 'Rocket'),
  ('Competition', 'Contests with prizes.', 'Medal'),
  ('Seminar', 'Talks by speakers and experts.', 'Mic')
on conflict (name) do nothing;

-- Clubs and organizers
insert into public.clubs (name, category, description) values
  ('Technical Council', 'Technical', 'Technical Council organises technical events on campus.'),
  ('AI/ML Club', 'Workshop', 'AI/ML Club organises workshop events on campus.'),
  ('Coding Club', 'Hackathon', 'Coding Club organises hackathon events on campus.'),
  ('Sports Committee', 'Sports', 'Sports Committee organises sports events on campus.'),
  ('Cultural Committee', 'Cultural', 'Cultural Committee organises cultural events on campus.'),
  ('Cyber Security Cell', 'Seminar', 'Cyber Security Cell organises seminar events on campus.'),
  ('E-Cell', 'Seminar', 'E-Cell organises seminar events on campus.'),
  ('Robotics Club', 'Workshop', 'Robotics Club organises workshop events on campus.'),
  ('Photography Club', 'Competition', 'Photography Club organises competition events on campus.'),
  ('Music Club', 'Cultural', 'Music Club organises cultural events on campus.'),
  ('Computer Science Society', 'Workshop', 'Computer Science Society organises workshop events on campus.'),
  ('Literary Club', 'Competition', 'Literary Club organises competition events on campus.'),
  ('Training and Placement Cell', 'Seminar', 'Training and Placement Cell organises seminar events on campus.')
on conflict (name) do nothing;

-- Venues (capacity = largest seeded event held there; adjust in the database if needed)
insert into public.venues (name, capacity) values
  ('Main Auditorium', 200),
  ('Seminar Hall B', 80),
  ('Innovation Lab', 150),
  ('Central Sports Ground', 500),
  ('Open Air Theatre', 400),
  ('Lecture Hall 3', 150),
  ('Computer Lab 2', 100),
  ('Convention Centre', 250),
  ('Robotics Lab', 60),
  ('Art Gallery Corridor', 90),
  ('Computer Lab 1', 70),
  ('Football Ground', 220),
  ('Lecture Hall 2', 80)
on conflict (name) do nothing;

-- Events. legacy_id is the id used by the old mock data, so the mapping stays stable.
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (1, 'TechFest 2026', 'The flagship technology festival of the campus with project expos, tech talks and live demos from student teams.',
  (select id from public.event_categories where name = 'Technical'),
  (select id from public.clubs where name = 'Technical Council'),
  (select id from public.departments where code = 'CSE'),
  (select id from public.venues where name = 'Main Auditorium'),
  '2026-10-12', '10:00', 200, '2026-10-10', 'registration_open',
  array['Carry your college ID card.', 'Teams can have up to 4 members.', 'Projects must be original work.', 'Judges'' decisions are final.']::text[], array['Best project: ₹15,000', 'Runner-up: ₹8,000', 'Best innovation: ₹5,000']::text[], '[{"time":"10:00 AM","activity":"Inauguration and welcome"},{"time":"11:00 AM","activity":"Project expo opens"},{"time":"1:00 PM","activity":"Lunch break"},{"time":"2:30 PM","activity":"Tech talks"},{"time":"4:30 PM","activity":"Awards and closing"}]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (2, 'AI & Machine Learning Workshop', 'A hands-on session on building and evaluating your first machine learning model with Python.',
  (select id from public.event_categories where name = 'Workshop'),
  (select id from public.clubs where name = 'AI/ML Club'),
  (select id from public.departments where code = 'IT'),
  (select id from public.venues where name = 'Seminar Hall B'),
  '2026-10-15', '14:00', 80, '2026-10-13', 'registration_open',
  array['Bring a laptop with Python installed.', 'Only registered participants can attend.']::text[], '{}'::text[], '[{"time":"2:00 PM","activity":"Introduction to machine learning"},{"time":"2:45 PM","activity":"Hands-on: training your first model"},{"time":"4:00 PM","activity":"Tea break"},{"time":"4:15 PM","activity":"Evaluating and improving models"},{"time":"5:00 PM","activity":"Questions and wrap-up"}]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (3, 'Inter-College Hackathon', 'A 24-hour hackathon where teams from nearby colleges build solutions for real campus problems.',
  (select id from public.event_categories where name = 'Hackathon'),
  (select id from public.clubs where name = 'Coding Club'),
  (select id from public.departments where code = 'CSE'),
  (select id from public.venues where name = 'Innovation Lab'),
  '2026-10-18', '09:00', 150, '2026-10-15', 'registration_open',
  array['Teams of 2 to 4 members.', 'All code must be written during the event.', 'Open-source libraries are allowed.', 'Every team must present a working demo.']::text[], array['First place: ₹30,000', 'Second place: ₹15,000', 'Best campus impact idea: ₹10,000']::text[], '[{"time":"9:00 AM","activity":"Team check-in"},{"time":"10:00 AM","activity":"Problem statements announced"},{"time":"10:30 AM","activity":"Hacking begins"},{"time":"Next day, 9:00 AM","activity":"Submissions close"},{"time":"Next day, 11:00 AM","activity":"Demos and results"}]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (4, 'Annual Sports Meet', 'Three days of track, field and team events with participation from every department.',
  (select id from public.event_categories where name = 'Sports'),
  (select id from public.clubs where name = 'Sports Committee'),
  (select id from public.departments where code = 'PE'),
  (select id from public.venues where name = 'Central Sports Ground'),
  '2026-10-22', '08:30', 500, '2026-10-19', 'registration_open',
  array['Wear proper sports attire and shoes.', 'Report 30 minutes before your event.', 'Referee decisions are final.']::text[], array['Medals for the top three in each event', 'Overall department trophy']::text[], '[{"time":"8:30 AM","activity":"Team check-in"},{"time":"9:30 AM","activity":"Opening march past"},{"time":"10:30 AM","activity":"Track and field heats"},{"time":"2:00 PM","activity":"Team event finals"},{"time":"4:30 PM","activity":"Medal ceremony"}]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (5, 'Cultural Night', 'An evening of music, dance and drama performed by students from across the campus.',
  (select id from public.event_categories where name = 'Cultural'),
  (select id from public.clubs where name = 'Cultural Committee'),
  (select id from public.departments where code = 'ARTS'),
  (select id from public.venues where name = 'Open Air Theatre'),
  '2026-10-25', '18:00', 400, '2026-10-23', 'registration_open',
  array['Each act is limited to 8 minutes.', 'Submit music tracks one day before the event.', 'Bring your own props and costumes.']::text[], array['Best performance award', 'Audience favourite award']::text[], '[{"time":"5:30 PM","activity":"Gates open"},{"time":"6:00 PM","activity":"Opening performance"},{"time":"6:30 PM","activity":"Group performances"},{"time":"8:00 PM","activity":"Solo showcase"},{"time":"9:15 PM","activity":"Closing and acknowledgements"}]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (6, 'Cyber Security Seminar', 'Industry speakers explain modern threats, safe coding habits and careers in cyber security.',
  (select id from public.event_categories where name = 'Seminar'),
  (select id from public.clubs where name = 'Cyber Security Cell'),
  (select id from public.departments where code = 'IT'),
  (select id from public.venues where name = 'Lecture Hall 3'),
  '2026-10-28', '11:00', 120, '2026-10-26', 'registration_open',
  array['Take your seat 15 minutes early.', 'Keep mobile phones on silent.']::text[], '{}'::text[], '[{"time":"11:00 AM","activity":"Welcome address"},{"time":"11:15 AM","activity":"Keynote on modern cyber threats"},{"time":"12:15 PM","activity":"Panel discussion"},{"time":"1:00 PM","activity":"Audience questions"}]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (7, 'Coding Competition', 'Solve algorithmic problems against the clock in this individual competitive programming contest.',
  (select id from public.event_categories where name = 'Competition'),
  (select id from public.clubs where name = 'Coding Club'),
  (select id from public.departments where code = 'CSE'),
  (select id from public.venues where name = 'Computer Lab 2'),
  '2026-11-02', '10:30', 100, '2026-10-30', 'registration_open',
  array['Individual participation only.', 'No mobile phones during the rounds.', 'Bring your college ID card.', 'Malpractice leads to disqualification.']::text[], array['First place: ₹6,000', 'Second place: ₹4,000', 'Third place: ₹2,000']::text[], '[{"time":"10:30 AM","activity":"Rules briefing"},{"time":"11:00 AM","activity":"Round 1"},{"time":"12:30 PM","activity":"Break"},{"time":"1:30 PM","activity":"Final round"},{"time":"3:00 PM","activity":"Results announced"}]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (8, 'Entrepreneurship Summit', 'Founders and investors share lessons on turning student ideas into real startups.',
  (select id from public.event_categories where name = 'Seminar'),
  (select id from public.clubs where name = 'E-Cell'),
  (select id from public.departments where code = 'BBA'),
  (select id from public.venues where name = 'Convention Centre'),
  '2026-11-06', '09:30', 250, '2026-11-04', 'registration_open',
  array['Carry your college ID card.', 'Entry is only for registered participants.']::text[], '{}'::text[], '[{"time":"9:30 AM","activity":"Registration and welcome"},{"time":"10:00 AM","activity":"Opening keynote"},{"time":"11:30 AM","activity":"Founders'' panel"},{"time":"1:00 PM","activity":"Lunch break"},{"time":"2:00 PM","activity":"Student startup showcase"},{"time":"4:00 PM","activity":"Closing remarks"}]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (9, 'Robotics Workshop', 'Build and program a line-following robot in a single afternoon with guided mentors.',
  (select id from public.event_categories where name = 'Workshop'),
  (select id from public.clubs where name = 'Robotics Club'),
  (select id from public.departments where code = 'ECE'),
  (select id from public.venues where name = 'Robotics Lab'),
  '2026-11-09', '13:00', 60, '2026-11-07', 'registration_open',
  array['Work in teams of 2.', 'Kits are provided and must be returned at the end.']::text[], '{}'::text[], '[{"time":"1:00 PM","activity":"Introduction to the robot kit"},{"time":"1:45 PM","activity":"Building the chassis and wiring"},{"time":"3:15 PM","activity":"Programming the line follower"},{"time":"4:30 PM","activity":"Test runs"}]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (10, 'Photography Competition', 'Students submitted photographs on the theme "Campus in Motion". Winners were announced at the gallery.',
  (select id from public.event_categories where name = 'Competition'),
  (select id from public.clubs where name = 'Photography Club'),
  (select id from public.departments where code = 'ARTS'),
  (select id from public.venues where name = 'Art Gallery Corridor'),
  '2026-09-15', '10:00', 90, '2026-09-10', 'completed',
  array['Photographs must follow the theme "Campus in Motion".', 'One entry per participant.', 'Only minor editing such as cropping and exposure is allowed.']::text[], array['First place: ₹3,000', 'Second place: ₹2,000', 'Third place: ₹1,000']::text[], '[]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (11, 'Web Development Bootcamp', 'A practical bootcamp covering HTML, CSS and React by building a small event website together.',
  (select id from public.event_categories where name = 'Workshop'),
  (select id from public.clubs where name = 'Coding Club'),
  (select id from public.departments where code = 'CSE'),
  (select id from public.venues where name = 'Computer Lab 1'),
  '2026-11-14', '10:00', 70, '2026-11-12', 'registration_open',
  array['Bring a laptop and charger.', 'Install Node.js and VS Code before the day.']::text[], '{}'::text[], '[{"time":"10:00 AM","activity":"HTML and CSS basics"},{"time":"11:30 AM","activity":"JavaScript fundamentals"},{"time":"1:00 PM","activity":"Lunch break"},{"time":"2:00 PM","activity":"Building a small site with React"},{"time":"4:00 PM","activity":"Demo and feedback"}]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (12, 'Inter-Department Football League', 'Departments compete in a knockout football league played over two weekends.',
  (select id from public.event_categories where name = 'Sports'),
  (select id from public.clubs where name = 'Sports Committee'),
  (select id from public.departments where code = 'PE'),
  (select id from public.venues where name = 'Football Ground'),
  '2026-11-20', '16:00', 220, '2026-11-17', 'registration_open',
  array['Each department fields one team.', 'Squads can have up to 15 players.', 'Wear a team jersey and shin guards.', 'Referee decisions are final.']::text[], array['Champions: trophy', 'Runners-up: trophy']::text[], '[{"time":"3:30 PM","activity":"Team reporting"},{"time":"4:00 PM","activity":"First match kick-off"},{"time":"5:30 PM","activity":"Second match kick-off"}]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (13, 'Battle of Bands', 'Student bands perform original and cover sets, judged by local musicians.',
  (select id from public.event_categories where name = 'Cultural'),
  (select id from public.clubs where name = 'Music Club'),
  (select id from public.departments where code = 'ARTS'),
  (select id from public.venues where name = 'Open Air Theatre'),
  '2026-12-05', '18:30', 300, '2026-12-02', 'registration_open',
  array['Each band gets a 20-minute set.', 'Bands can have up to 6 members.', 'Bring your own instruments. A drum kit is provided.']::text[], array['First place: ₹10,000', 'Second place: ₹5,000']::text[], '[{"time":"6:00 PM","activity":"Gates open"},{"time":"6:30 PM","activity":"Opening and sound check"},{"time":"7:00 PM","activity":"Band performances"},{"time":"9:00 PM","activity":"Judges'' results"}]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (14, 'Python Programming Workshop', 'A beginner-friendly workshop on Python basics, taught through small hands-on exercises.',
  (select id from public.event_categories where name = 'Workshop'),
  (select id from public.clubs where name = 'Computer Science Society'),
  (select id from public.departments where code = 'CSE'),
  (select id from public.venues where name = 'Computer Lab 1'),
  '2026-08-22', '10:00', 60, '2026-08-19', 'completed',
  '{}'::text[], '{}'::text[], '[]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (15, 'Campus Code Sprint', 'A 12-hour team build challenge where students prototyped ideas for everyday campus problems.',
  (select id from public.event_categories where name = 'Hackathon'),
  (select id from public.clubs where name = 'Computer Science Society'),
  (select id from public.departments where code = 'CSE'),
  (select id from public.venues where name = 'Innovation Lab'),
  '2026-07-26', '09:00', 100, '2026-07-23', 'completed',
  '{}'::text[], '{}'::text[], '[]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (16, 'Freshers'' Welcome Fest', 'A welcome evening of performances and games for first-year students, run by student volunteers.',
  (select id from public.event_categories where name = 'Cultural'),
  (select id from public.clubs where name = 'Cultural Committee'),
  (select id from public.departments where code = 'ARTS'),
  (select id from public.venues where name = 'Open Air Theatre'),
  '2026-08-30', '17:00', 350, '2026-08-27', 'completed',
  '{}'::text[], '{}'::text[], '[]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (17, 'Inter-Department Quiz', 'A general knowledge and campus trivia quiz played between department teams.',
  (select id from public.event_categories where name = 'Competition'),
  (select id from public.clubs where name = 'Literary Club'),
  (select id from public.departments where code = 'ARTS'),
  (select id from public.venues where name = 'Lecture Hall 2'),
  '2026-09-05', '11:00', 80, '2026-09-02', 'completed',
  '{}'::text[], '{}'::text[], '[]'::jsonb)
on conflict (legacy_id) do nothing;
insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (18, 'Career Guidance Seminar', 'A session on internships, placements and planning a career path, led by the placement cell.',
  (select id from public.event_categories where name = 'Seminar'),
  (select id from public.clubs where name = 'Training and Placement Cell'),
  (select id from public.departments where code = 'BBA'),
  (select id from public.venues where name = 'Lecture Hall 3'),
  '2026-09-26', '11:00', 150, '2026-09-23', 'completed',
  '{}'::text[], '{}'::text[], '[]'::jsonb)
on conflict (legacy_id) do nothing;
