// Generates supabase/seed.sql from the original CampusFlow event data (supabase/seed-data/events.mjs).
// Usage: node scripts/generate-seed.mjs
// The seed only contains foundational data: departments, categories, clubs, venues and the published events.
// It contains NO user accounts, passwords or secrets. Seeded events start with no registrations.
import { writeFileSync } from 'node:fs';
import { events, CATEGORY_LIST, DEPARTMENTS } from '../supabase/seed-data/events.mjs';

const q = (value) => (value === null || value === undefined ? 'null' : `'${String(value).replace(/'/g, "''")}'`);
const textArray = (list) => (list && list.length ? `array[${list.map(q).join(', ')}]::text[]` : `'{}'::text[]`);

const DEPARTMENT_CODES = {
  'Computer Science': 'CSE', 'Information Technology': 'IT', Electronics: 'ECE',
  'Business Studies': 'BBA', 'Arts & Design': 'ARTS', 'Physical Education': 'PE',
};
const CATEGORY_INFO = {
  Technical: ['Tech talks, expos and project showcases.', 'Cpu'],
  Workshop: ['Hands-on sessions to build new skills.', 'Wrench'],
  Hackathon: ['Team build challenges.', 'Rocket'],
  Sports: ['Tournaments, leagues and meets.', 'Trophy'],
  Cultural: ['Music, dance, drama and art.', 'Palette'],
  Seminar: ['Talks by speakers and experts.', 'Mic'],
  Competition: ['Contests with prizes.', 'Medal'],
};

const to24 = (text) => {
  const m = /^(\d{1,2}):(\d{2})\s*(AM|PM)$/i.exec(text);
  let h = Number(m[1]) % 12;
  if (m[3].toUpperCase() === 'PM') h += 12;
  return `${String(h).padStart(2, '0')}:${m[2]}`;
};

const out = [];
out.push('-- CampusFlow seed data. Generated by scripts/generate-seed.mjs. Safe to run more than once.');
out.push('-- Contains no users, passwords or secrets. Run AFTER migrations/001_initial_schema.sql.\n');

out.push('-- Departments');
out.push('insert into public.departments (name, code) values');
out.push(DEPARTMENTS.map((d) => `  (${q(d)}, ${q(DEPARTMENT_CODES[d])})`).join(',\n'));
out.push('on conflict (name) do nothing;\n');

out.push('-- Event categories');
out.push('insert into public.event_categories (name, description, icon) values');
out.push(CATEGORY_LIST.map((c) => `  (${q(c)}, ${q(CATEGORY_INFO[c][0])}, ${q(CATEGORY_INFO[c][1])})`).join(',\n'));
out.push('on conflict (name) do nothing;\n');

// Clubs: every organizer that appears on an event; category = the most common category of its events
const clubs = {};
events.forEach((e) => {
  clubs[e.organizer] = clubs[e.organizer] || {};
  clubs[e.organizer][e.category] = (clubs[e.organizer][e.category] || 0) + 1;
});
out.push('-- Clubs and organizers');
out.push('insert into public.clubs (name, category, description) values');
out.push(Object.entries(clubs).map(([name, cats]) => {
  const category = Object.entries(cats).sort((a, b) => b[1] - a[1])[0][0];
  return `  (${q(name)}, ${q(category)}, ${q(`${name} organises ${category.toLowerCase()} events on campus.`)})`;
}).join(',\n'));
out.push('on conflict (name) do nothing;\n');

// Venues: capacity starts as the largest event held there. Admins can change it later.
const venues = {};
events.forEach((e) => { venues[e.venue] = Math.max(venues[e.venue] || 0, e.capacity); });
out.push('-- Venues (capacity = largest seeded event held there; adjust in the database if needed)');
out.push('insert into public.venues (name, capacity) values');
out.push(Object.entries(venues).map(([name, cap]) => `  (${q(name)}, ${cap})`).join(',\n'));
out.push('on conflict (name) do nothing;\n');

out.push('-- Events. legacy_id is the id used by the old mock data, so the mapping stays stable.');
events.forEach((e) => {
  const status = e.status === 'Completed' ? 'completed' : 'registration_open';
  const schedule = JSON.stringify((e.schedule || []).map(([time, activity]) => ({ time, activity })));
  out.push(`insert into public.events (legacy_id, title, description, category_id, club_id, department_id, venue_id, event_date, start_time, capacity, registration_deadline, status, rules, prizes, schedule)
values (${e.id}, ${q(e.title)}, ${q(e.description)},
  (select id from public.event_categories where name = ${q(e.category)}),
  (select id from public.clubs where name = ${q(e.organizer)}),
  (select id from public.departments where code = ${q(DEPARTMENT_CODES[e.department])}),
  (select id from public.venues where name = ${q(e.venue)}),
  ${q(e.date)}, ${q(to24(e.time))}, ${e.capacity}, ${q(e.registrationDeadline)}, ${q(status)},
  ${textArray(e.rules)}, ${textArray(e.prizes)}, ${q(schedule)}::jsonb)
on conflict (legacy_id) do nothing;`);
});

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), `${out.join('\n')}\n`);
console.log(`seed.sql written: ${events.length} events, ${Object.keys(clubs).length} clubs, ${Object.keys(venues).length} venues`);
